# Generated by Django 6.0.3 on 2026-06-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_ID', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=1000)),
                ('Image', models.ImageField(upload_to='image')),
                ('Qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=50)),
                ('Employer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teachers')),
            ],
        ),
    ]
