# Generated by Django 6.0.3 on 2026-06-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teachers_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='Subjects jo yeh teacher padha sakta hai (comma separated)', max_length=200),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Employee_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Image',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Last_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Qualification',
            field=models.CharField(max_length=200),
        ),
    ]
