# Generated by Django 6.0.3 on 2026-06-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_teachers_specialization_alter_teachers_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='Gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
