# Generated by Django 6.0.3 on 2026-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_teachers_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Gender',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
