# Generated by Django 6.0.3 on 2026-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_remove_teachers_gender_teachers_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
