# Generated by Django 6.0.3 on 2026-06-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_alter_teachers_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Title',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='Subjects that teacher can teach (comma separated)', max_length=200),
        ),
    ]
