# Generated by Django 6.0.3 on 2026-06-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_remove_teachers_title_alter_teachers_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='Title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
