# Generated by Django 6.0.3 on 2026-06-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_teachers_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='specialization',
        ),
    ]
