# Generated by Django 6.0.3 on 2026-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_remove_teachers_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='Subjects that teacher can teach (comma separated)', max_length=200),
        ),
    ]
