# Generated by Django 6.0.3 on 2026-06-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cnic', models.CharField(max_length=30)),
                ('pas', models.CharField(max_length=20)),
            ],
        ),
    ]
