# Generated by Django 6.0.3 on 2026-06-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=50)),
                ('section_limit', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S', models.CharField(max_length=50)),
                ('grade', models.ManyToManyField(related_name='subjects', to='cls.grade')),
            ],
        ),
    ]
