# Generated by Django 6.0.3 on 2026-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0002_remove_grade_section_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
