# Generated by Django 6.0.3 on 2026-06-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0003_section_student_count_alter_section_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='student_count',
        ),
    ]
