# Generated by Django 6.0.3 on 2026-06-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('F_Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(default='', max_length=1000)),
                ('Image', models.ImageField(default='', upload_to='image')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cls.grade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_set', to='cls.section')),
            ],
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=10)),
                ('Roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
    ]
