# Generated by Django 6.0.3 on 2026-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Contact',
            field=models.CharField(max_length=20),
        ),
    ]
