# Generated by Django 6.0.3 on 2026-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='E_mail',
            field=models.EmailField(default='test@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='F_CNIC',
            field=models.CharField(default='', max_length=50),
        ),
    ]
