# Generated by Django 6.0.3 on 2026-06-21 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_e_mail_students_f_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='F_CNIC',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='CNIC must be 36102-1313450-9 format', regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
    ]
