# Generated by Django 6.0.3 on 2026-06-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=50)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.section')),
            ],
        ),
    ]
