# Generated by Django 6.0.3 on 2026-06-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0001_initial'),
        ('manager', '0002_teacherattendance_teachersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='Subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='assigned',
            unique_together={('Employee_ID', 'Subject', 'clas')},
        ),
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.IntegerField(default=10, help_text='Har mahine ki kitarikh tak fee jama ho')),
                ('late_fine', models.DecimalField(decimal_places=2, default=0, help_text='Late submission par extra charge', max_digits=8)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.grade', unique=True)),
            ],
        ),
    ]
