# Generated by Django 6.0.3 on 2026-06-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0001_initial'),
        ('manager', '0003_alter_assigned_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfee',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classfee',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classfee',
            name='due_date',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='classfee',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cls.grade'),
        ),
        migrations.AlterField(
            model_name='classfee',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='classfee',
            unique_together={('grade', 'month', 'year')},
        ),
    ]
